services:
  seventy7diamonds.payments.api:
    image: seventy7diamonds.payments.api
    build:
      context: .
      dockerfile: PaymentAPI/Seventy7Diamonds.Payments.Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - redis
      - postgres
      
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:"/var/lib/postgresql/data

volumes:
  postgres-data:
    